server:
  port: 9090

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${Album.datasource.driver-class-name}
    url: jdbc:mysql://${Album.datasource.host}:${Album.datasource.port}/${Album.datasource.database}?serverTimezone=UTC&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${Album.datasource.username}
    password: ${Album.datasource.password}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.album.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      album:
        mapper: debug
        service: info
        controller: info



